//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleDwarfsAgencyMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCharge
    {
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<double> DailyHours { get; set; }
        public Nullable<double> AgencyCharge { get; set; }
        public decimal Limit { get; set; }
        public Nullable<double> LocalAuthCharge { get; set; }
        public Nullable<double> ClientChargeNormalHours { get; set; }
        public Nullable<double> ClientChargeExtraHours { get; set; }
    }
}
