//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleDwarfsAgencyMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceList
    {
        public int Id { get; set; }
        public int Invoice { get; set; }
        public System.DateTime Weekending { get; set; }
        public int Timesheet { get; set; }
        public double HoursWorked { get; set; }
        public double Rate { get; set; }
        public double Cost { get; set; }
    }
}
