//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleDwarfsAgencyMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LittleDwarfAgencyEntities1 : DbContext
    {
        public LittleDwarfAgencyEntities1()
            : base("name=LittleDwarfAgencyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvoiceList> InvoiceLists { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Timesheet> Timesheets { get; set; }
        public virtual DbSet<WorkPeriod> WorkPeriods { get; set; }
        public virtual DbSet<DailyCharge> DailyCharges { get; set; }
        public virtual DbSet<PeriodRate> PeriodRates { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int ClearAllTablesProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearAllTablesProcedure");
        }
    
        public virtual int ClearInvoiceListsTableProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearInvoiceListsTableProcedure");
        }
    
        public virtual int ClearInvoicesTableProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearInvoicesTableProcedure");
        }
    
        public virtual int ClearTimesheetsTableProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearTimesheetsTableProcedure");
        }
    
        public virtual int ClearWorkPeriodsTableProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearWorkPeriodsTableProcedure");
        }
    
        public virtual int MakeAllTablesProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MakeAllTablesProcedure");
        }
    }
}
