//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleDwarfsAgencyMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPeriod
    {
        public int Id { get; set; }
        public int Timesheet { get; set; }
        public System.DateTime PeriodDate { get; set; }
        public double AllocHours { get; set; }
        public System.TimeSpan TimeIn { get; set; }
        public System.TimeSpan TimeExit { get; set; }
        public string ActualService { get; set; }
    }
}
